name: Upload files to S3
# https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#workflow_run
# https://stackoverflow.com/questions/58457140/dependencies-between-workflows-on-github-actions
on:
  workflow_run:
    workflows: ["Test Policies"]
    branches: [master]
    types:
      - completed
permissions:
      id-token: write
      contents: read
jobs:
  policy_list:
    name: "Policy List"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          # ruby-version: 2.4.1 # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Generate policy list
        shell: bash -l {0} # https://github.com/actions/virtual-environments/issues/4
        run: |
          bundle install --without documentation --path bundle
          bundle exec rake generate_policy_list
      - name: Upload to s3
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::023366516001:role/rs-policysync-tools-github-actions
          role-session-name: uploadactivepolicylist
          aws-region: us-east-1
      # Upload a file to AWS s3
      - name:  Copy active-policy-list.json to s3
        run: |
          aws s3 cp ./dist/active-policy-list.json s3://rs-policysync-tool/active-policy-list.json --acl public-read-write
